// Code generated by godddx, DO AVOID EDIT.
package recordingdb

import (
	"github.com/gowvp/owl/internal/core/recording"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ recording.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Begin 开启事务
func (d DB) Begin() (orm.Tx, error) {
	return orm.Begin(d.db)
}

// Recording Get business instance
func (d DB) Recording() recording.RecordingStorer {
	return Recording(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	models := []any{
		new(recording.RecordingPlan),
		new(recording.ChannelRecordingPlan),
	}
	// Recording plan tables are part of the current runtime contract and must
	// exist even when legacy/global auto-migration is disabled in a packaged
	// deployment. They are additive and safe for existing databases.
	if ok {
		models = append([]any{new(recording.Recording)}, models...)
	}
	if err := d.db.AutoMigrate(models...); err != nil {
		panic(err)
	}
	return d
}
